---
title: "ABQ Spatial Neighborhood Matrices"
output: html_document
date: "2025-04-03"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, paged.print = FALSE)
```

# Spatial Neighborhood Matrices for Albuquerque

Based on <https://www.paulamoraga.com/book-spatial/spatial-neighborhood-matrices.html>

I will use elementary and middle school districts.

```{r}
library(spData)
library(sf)
library(spdep)
library(ggplot2)
library(lattice)
```

```{r}
unzip("exdata/ABQ/ElemSchoolServiceAreas.kmz", exdir = "data/ABQ/")
map_elem <- read_sf("data/ABQ/doc.kml") |> 
  st_transform(32113)
unzip("exdata/ABQ/MidSchoolServiceAreas.kmz", exdir = "data/ABQ/")
map_mid <- read_sf("data/ABQ/doc.kml") |> 
  st_transform(32113)
```

```{r}
st_crs(map_mid)
```

## Contiguity

```{r}
nb_elem <- poly2nb(map_elem, queen = TRUE, snap = 1)
head(nb_elem)
```

```{r}
nb_mid <- poly2nb(map_mid, queen = TRUE)
head(nb_mid)
```

```{r}
plot(st_geometry(map_mid), border = "lightgray")
plot.nb(nb_mid, st_geometry(map_mid), add = TRUE)
```

```{r}
plot(st_geometry(map_elem), border = "lightgray")
plot.nb(nb_elem, st_geometry(map_elem), add = TRUE)
```

```{r}
id <- 25
map_elem$neighbors <- "other"
map_elem$neighbors[id] <- "area"
map_elem$neighbors[nb_elem[[id]]] <- "neighbors"

ggplot(map_elem) +
  geom_sf(aes(fill = neighbors)) +
  #coord_sf(xlim = c(-106.8,-106.4), ylim = c(35.0, 35.2)) +
  coord_sf(xlim = c(455000, 480000),
           ylim = c(445000,470000)) +
  theme_bw()
```

```{r}
id <- 12
map_mid$neighbors <- "other"
map_mid$neighbors[id] <- "area"
map_mid$neighbors[nb_mid[[id]]] <- "neighbors"

ggplot(map_mid) +
  geom_sf(aes(fill = neighbors)) +
  coord_sf(xlim = c(455000, 480000),
           ylim = c(445000,470000)) +
  theme_bw()
```

## K-Nearest Neighbors

```{r warning=FALSE}
coo <- st_centroid(map_elem)
nb <- knn2nb(knearneigh(coo, k = 3))
plot(st_geometry(map_elem), border = "lightgray")
plot.nb(nb, st_geometry(map_elem), add = T)
```

```{r warning=FALSE}
coo <- st_centroid(map_mid)
nb <- knn2nb(knearneigh(coo, k = 3))
plot(st_geometry(map_mid), border = "lightgray")
plot.nb(nb, st_geometry(map_mid), add = T)
```

## Distance Neighbors

```{r}
coo <- st_centroid(map_mid)
dist1_mid <- knn2nb(knearneigh(coo, k = 1)) |> 
  nbdists(coo)
summary(unlist(dist1_mid))
```

```{r warning=FALSE}
nb <- dnearneigh(x = st_centroid(map_mid), d1 = 0, d2 = 8000)
plot(st_geometry(map_mid), border = "lightgrey")
plot.nb(nb, st_geometry(map_mid), add = TRUE)
```

```{r}
coo <- st_centroid(map_elem)
dist1_elem <- knn2nb(knearneigh(coo, k = 1)) |> 
  nbdists(coo)
summary(unlist(dist1_elem))
```

```{r warning=FALSE}
nb <- dnearneigh(x = st_centroid(map_elem), d1 = 0, d2 = 4000)
plot(st_geometry(map_elem), border = "lightgrey")
plot.nb(nb, st_geometry(map_elem), add = TRUE)
```

## order-k based

> Fist order

```{r}
nb <- poly2nb(map_elem, snap = 1)
nblags <- nblag(neighbours = nb, maxlag = 2)
plot(st_geometry(map_elem), border = "lightgray")
plot.nb(nblags[[1]], st_geometry(map_elem), add = TRUE)
```

> Second order

```{r}
plot(st_geometry(map_elem), border = "lightgray")
plot.nb(nblags[[2]], st_geometry(map_elem), add = TRUE)
```

> Cumulative order

```{r}
nb <- poly2nb(map_elem, snap = 1)
nblags <- nblag(neighbours = nb, maxlag = 2)
nblags_cum <- nblag_cumul(nblags)
plot(st_geometry(map_elem), border = "lightgray")
plot.nb(nblags_cum, st_geometry(map_elem), add = TRUE)
```

## Spatial weights matrix based on binary neighbors

```{r}
nb_elem <- poly2nb(map_elem, snap = 1)
nbw_elem <- nb2listw(nb_elem, style = "W")
nbw_elem$weights[1:3]
```

```{r}
nb_mid <- poly2nb(map_mid, snap = 1)
nbw_mid <- nb2listw(nb_mid, style = "W")
nbw_mid$weights[1:3]
```

```{r}
m1_elem <- listw2mat(nbw_elem)
levelplot(t(m1_elem),
          scales = list(y = list(at = c(20, 40, 60, 80),
                                 labels = c(20, 40, 60, 80))))
```

```{r}
m1_mid <- listw2mat(nbw_mid)
levelplot(t(m1_mid),
          scales = list(y = list(at = c(20, 40, 60, 80),
                                 labels = c(20, 40, 60, 80))))
```

## Spatial weights based on inverse distance

```{r}
coo <- st_centroid(map_mid)
nb_mid <- poly2nb(map_mid)
dists <- nbdists(nb_mid, coo)
ids <- lapply(dists, function(x){1/x})
nbw_mid <- nb2listw(nb_mid, glist = ids, style = "B")
nbw_mid$weights[1:3]
```

```{r}
m2_mid <- listw2mat(nbw_mid)
levelplot(t(m2_mid),
          scales = list(y = list(at = c(5, 10, 15, 20, 25),
                                 labels = c(5, 10, 15, 20, 25))))
```

```{r}
coo <- st_centroid(map_elem)
nb_elem <- poly2nb(map_elem)
dists <- nbdists(nb_elem, coo)
ids <- lapply(dists, function(x){1/x})
nbw_elem <- nb2listw(nb_elem, glist = ids, style = "B",
                     zero.policy = TRUE)
nbw_elem$weights[1:3]
```

```{r}
m2_elem <- listw2mat(nbw_elem)
levelplot(t(m2_elem),
          scales = list(y = list(at = c(5, 10, 15, 20, 25),
                                 labels = c(5, 10, 15, 20, 25))))
```
